modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"
issueTrackerURL="https://github.com/kelcok22/Kamen_Rider_Craft/issues/"

[[mods]]
modId="kamenridercraft" #mandatory
version="1.0.9"
displayName="Kamen Rider Craft"
displayURL="https://discord.gg/3b37BRX/"
logoFile="logo.png"
authors="Kelco_K22, LiasDan, Axos, Chair, DocRider, HosephHoestar, AndrewBean, Blurtle, Trainfanz"
description='''Kamen Rider Craft began as a small project I started in late 2012, and has since evolved into a massive mod with hundreds of items, weapons, and forms with multiple developers on board. Back at the start of 2023 I decided to start to recode this mod from scratch. With the goal to make the mod a lot more friendly to work on, now over a year later there is still a lot of work to do, but I want to share it.'''

[[mixins]]
config="kamenridercraft.mixins.json"

[[dependencies.kamenridercraft]] #optional
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.kamenridercraft]]
modId="minecraft"
type="required"
versionRange="[1.21.1, 1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.kamenridercraft]]
modId="geckolib"
type="required"
reason = "GeckoLib is used for rendering the armor and some of the mobs."
versionRange="[4.8.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.kamenridercraft]]
modId="player_animation_library"
type="required"
reason = "Used for posing and attack animations."
versionRange="1.1.4+mc.1.21.1,)"
ordering="AFTER"
side="BOTH"